# Setup
title:               Mapping Carifesta Archives
tagline:             'A comprehensive and interactive map of Carifesta collections worldwide.'
description:         'Made by <a href="https://rjkooiker.github.io" target="_blank">René J. Kooiker</a>.'
url:                 https://carifest-archives.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              René J. Kooiker
  url:               https://rjkooiker.github.io
  email:             rkooiker18@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
